export const SDG_DATA = [
  { number: 1, name: "No Poverty", color: "#E5243B" },
  { number: 2, name: "Zero Hunger", color: "#DDA63A" },
  { number: 3, name: "Good Health", color: "#4C9F38" },
  { number: 4, name: "Quality Education", color: "#C5192D" },
  { number: 5, name: "Gender Equality", color: "#FF3A21" },
  { number: 6, name: "Clean Water", color: "#26BDE2" },
  { number: 7, name: "Clean Energy", color: "#FCC30B" },
  { number: 8, name: "Decent Work", color: "#A21942" },
  { number: 9, name: "Innovation", color: "#FD6925" },
  { number: 10, name: "Reduced Inequalities", color: "#DD1367" },
  { number: 11, name: "Sustainable Cities", color: "#FD9D24" },
  { number: 12, name: "Responsible Consumption", color: "#BF8B2E" },
  { number: 13, name: "Climate Action", color: "#3F7E44" },
  { number: 14, name: "Life Below Water", color: "#0A97D9" },
  { number: 15, name: "Life on Land", color: "#56C02B" },
  { number: 16, name: "Strong Institutions", color: "#00689D" },
  { number: 17, name: "Partnerships", color: "#19486A" },
];
